version: "2.0"
services:
  app: 
    build: .
    container_name: sads_batch_new
    command: streamlit run --server.headless true --server.port 8501 main.py 
    ports:
      - 8080:8501
    # volumes:
    #   - .:/app
